---
- hosts: localhost
  tasks:
   - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - font-hack-nerd-font
        state: present
        update_homebrew: yes